# Generated by Django 4.0.4 on 2022-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idLocalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]


