# Generated by Django 4.0.4 on 2022-05-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Localidad', '0001_initial'),
        ('Pais', '0001_initial'),
        ('obraSocial', '0001_initial'),
        ('Escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.BooleanField()),
                ('nac', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cel', models.IntegerField(null=True)),
                ('calle', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=50)),
                ('pmot', models.CharField(max_length=100)),
                ('dniTutor', models.IntegerField()),
                ('idEsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.escuela')),
                ('idLocalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localidad.localidad')),
                ('idObra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obraSocial.obrasocial')),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pais.pais')),
            ],
        ),
    ]
