# Generated by Django 4.0.4 on 2022-05-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_fecha_registro_alter_persona_cel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre']},
        ),
    ]
