# Generated by Django 4.0.4 on 2022-05-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activation_code',
            field=models.CharField(default=810506512977, max_length=254),
        ),
    ]
