# Generated by Django 4.0.4 on 2022-05-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_activator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activator',
            name='activation_code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
