# Generated by Django 4.0.4 on 2022-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_activator_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='activator',
            name='activation_code_encoded',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
