# Generated by Django 4.0.4 on 2022-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='escuela',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
